### ISSUE TITLE
The privacy policy popup should be shown once only

### ISSUE THREAD

**Issue by martinpoliak-goodai** [arayabrain/space-engineers-ai-spaceship-generator#54]
The privacy policy is shown every time I launch the executable. It should be shown once only, the very first time. A config file should remember my choice and also whether I successfully ran through the whole user study experiment. In such case it should always bring me to the same UI as clicking "no" on the privacy policy would.

**Comment by gallorob** [comment]
What happens if the user first declines the privacy policy and later wants to participate in the user study? As currently suggested, the user would be locked out by their first choice.

I would instead have the privacy popup show everytime the user launches the application _unless_ they finished the user study experiment. Would that work for you?

**Comment by martinpoliak-goodai** [comment]
OK, let's try it that way 👍

**Comment by gallorob** [comment]
Alright, I will have tackle this tomorrow 👍

**Comment by gallorob** [comment]
@martinpoliak-goodai Implemented in f607c8c91ad51e5cbd922f825e6e8222e2505879

At the end of the user study, the file `.userstudyover` is created. At launch, if the file exists, the application starts in User mode (unless `dev_mode` is specified) and the privacy policy modal is not shown anymore.
