### ISSUE TITLE
Voxel-based preview - make it optional + add fixes for disappearing blocks

### ISSUE THREAD

**Issue by martinpoliak-goodai** [arayabrain/space-engineers-ai-spaceship-generator#57]
The new voxel-based preview has its merits (I can see the spaceship in a compact way and also I can picture what it might look like if I am inside), but also drawbacks (the main pain point - it is difficult to "see" the shape of the ship from some angles and blocks keep appearing/disappearing as I rotate the ship).

Would it be possible to use the previous preview (with the spheres) as a default option and provide the voxel-based preview to the user through a checkbox?

In either case, the voxel-based preview will need to get some fixes - currently, ship blocks appear and disappear from the rendered view if I rotate the ship, including blocks like thrusters that should be on the ship face that is turned towards me.

**Comment by martinpoliak-goodai** [comment]
https://user-images.githubusercontent.com/14159877/195405467-b418c056-6b9d-46a4-baa4-bbed446e42a1.mp4

This video demonstrates the issue with blocks appearing & disappearing as I rotate the ship.

**Comment by gallorob** [comment]
@martinpoliak-goodai this seems to be an [open issue](https://plotly.com/python/reference/mesh3d/#mesh3d-opacity) related to the opacity setting in the Mesh3D Plotly object and how it is handled by the underlying OpenGL API. This mean it's unfortunately not something I can fix in the application.

However, I believe it is possible to use it in the application still. I like the idea of toggling the voxel preview on/off, but it is also possible to show both the scatter plot preview (the one with the spheres) as well as the voxel one! I'm attaching different options:
- Semitransparent voxel with scatter plot: 
![voxel05_scatter1](https://user-images.githubusercontent.com/32876132/195512768-611101b7-6578-4fa7-96e3-c8f8862254ee.gif)
This shows both the blocks in the correct place as well as giving a good overview of the voxelized spaceship. Additionally, having the spheres means the user wouldn't notice the disappearing faces of the voxels as much.
- Opaque voxel with transparent scatter plot:
![voxel1_scatter0](https://user-images.githubusercontent.com/32876132/195512779-babe1213-fbf0-402f-8c41-24dd61fff787.gif)
Here the voxel has no faces disappearing (since it's at full opacity), and you can zoom in/out to get an idea of the spaceships internal air blocks easily.

Let me know which of the options you'd prefer to have when toggling the voxel preview, however it is also possible to allow the user to choose the opacity level of the voxel preview (0 for full transparency, 1 for no transparency) via a slider below the spaceship preview instead.

**Comment by martinpoliak-goodai** [comment]
Actually, another last thought here :-) Since you can do transparency, could you make the window cubes semi-transparent / see-through?

**Comment by gallorob** [comment]
Great, I will implement this shortly.

As for the other points:
- it may be possible to adjust the sphere sizes, yes, but that would require firing an update for _every_ plot interaction (ie: scrolling, panning, rotating etc), which I believe will become too cumbersome for most cases. It is however possible to set the spheres to be smaller, which would alleviate the problem.
- transparency is applied per-plot, not per-vortex unfortunately. I can try add a separate vortex map exclusively for semi-transparent blocks (for now, just the windows) though, if it's not too much of a burden to render smoothly.

**Comment by gallorob** [comment]
Implemented in 894b2cf06017f39f55a63c15ae71ffc16aebff73

Here's a preview of the new behavior:
![toggle-example](https://user-images.githubusercontent.com/32876132/195553311-2c41efe9-565d-4ad0-aab1-8e8837b69fbb.gif)
You can also see that the windows are now slightly transparent (0.75 opacity), as well as the smaller spheres (1 unit smaller).

Closing the issue for now as all possible changes have been implemented.

**Comment by martinpoliak-goodai** [comment]
Thank you Roberto. I'd stick with the size=4 for the spheres if possible - could you revert that please? 
Could you please also remove the "Toggle Voxel Preview:" label and instead expand "Toggle" to "Voxel Preview"?

**Comment by gallorob** [comment]
Updated in 29856b88a7ef3e916ef52b562ed472a50518850b

Here's a preview of the changes:
![update_voxel_toggle](https://user-images.githubusercontent.com/32876132/195734428-938e8206-499e-48fe-91f3-38131fe43ada.gif)

I've also added the file `.userstudyover` if you want to test the behavior of the app after the user study is over (make sure it's in the same directory as the executable).
