### ISSUE TITLE
Fully utilizing the 3rd dimension

### ISSUE THREAD

**Issue by martinpoliak-goodai** [arayabrain/space-engineers-ai-spaceship-generator#72]
This is nothing urgent, just a thought - it seems that the generated ships are all "flat", that is, growing only in 2 dimensions. The 3rd spatial dimension is almost ignored when new solutions are proposed. For example, I have not seen a ship that would grow to occupy the space of a cube. Is there some explicit bias in the algorithm or a reason why growth in all 3 dimensions is not preferred?

**Comment by Kaixhin** [comment]
Is this still the case in "unsafe" mode?

**Comment by gallorob** [comment]
That's a valid question @martinpoliak-goodai! I can think of two main reasons why that may be:
1. The expansion rules (ie: which tile(s) should be replaced with which other tile(s) at each iteration) also control the mutations that take place (we select a few tiles each iteration to mutate). Therefore, if the rules are biased, so will be the resulting spaceships.
2. It is extremely easy for a spaceship to become invalid due to intersections, meaning that the (feasible) spaceships will probably have less or shorter branches.

To test it out, here are some spaceships obtained with "unbiased" rules after a couple of iterations:
![image](https://user-images.githubusercontent.com/32876132/198173998-bce9f8e5-3eb7-4f66-94d9-77167995b8ca.png)
![image](https://user-images.githubusercontent.com/32876132/198175635-92e1ed82-6478-400f-b0cd-af68e4da3ea1.png)

So I believe (2) is the main reason why we don't see many "cube-filling" spaceships. I created the [alt-rules ](https://github.com/arayabrain/space-engineers-ai-spaceship-generator/tree/alt-rules) branch if you want to safely play around with the high-level rules (edit the percentages in `hlrules` and `hlrules_sm`, each left-side rule should have a total probability of 1--there's a check for this).

Additionally, in previous work, we obtained feasible "cube-filling" spaceships after many more iterations, so it may be possible to find these type of spaceships by playing around with the hyperameters.

Finally, it is possible that they are not as high-performing as the "flat" spaceships, so they either wouldn't be displayed in the application, or discarded entirely.

Bit of a long explanation, but hopefully clears any doubt 😀

@Kaixhin yes, almost all mutations take place in the "body" section of the spaceships, which is unaffected by the un/safe mode.

**Comment by martinpoliak-goodai** [comment]
Thank you Roberto for the hints and for the branch; I suggest we keep this issue open for now (it's nothing urgent).

**Comment by gallorob** [comment]
@martinpoliak-goodai I played around with the rules some more, it seems that allowing terminal strings (ie: the specialized tiles) to be non-terminal actually helps quite a bit. For reference, here's a spaceship after just one generation (removed the external hull for clarity):

![image](https://user-images.githubusercontent.com/32876132/198962070-82257d2c-c82d-4a4f-a12a-044935e25712.png)

It may be worth it to publish these rules after the user study is over (since we already started collecting data we can't alter how the spaceships are generated) so that players can generate more complex spaceships.

**Comment by martinpoliak-goodai** [comment]
This looks great, Roberto, I'd definitely add it as a feature to the official download after the user study is over. I guess there could be a toggle for this feature in the Population controls? Also, please update the hint text in there so that users can understand what effect the toggle will have.
